---
- name: Preconfig
  hosts: kafka
  tasks:
    - name: Installing Docker
      block:
        - name: Adding universe
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present
        - name: apt update
          apt:
            update_cache: yes
        - name: Installing additional package
          apt:
            pkg:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg2
            - software-properties-common
            update_cache: yes

        - name: Adding key for Docker (Add Docker’s official GPG key:)
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
        - name: Installing stable repository Docker
          apt_repository:
            repo: >
              deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
              https://download.docker.com/linux/ubuntu
              {{ ansible_distribution_release }} stable
            state: present
            update_cache: yes
            filename: docker
        - name: Installing Docker-ce
          apt:
            name: docker-ce
            update_cache: true
        - name: Check that the Docker had been instaled and restarted (DOCKER COMPOSE)
          service:
            name: docker
            state: restarted
            enabled: true
      become: yes
    - name: Check last version of Docker-compose
      block:
        - name: Getting last version of Docker-compose
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page
        - name: Instaling last version of Docker-compose
          get_url:
            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
            dest: /usr/local/bin/docker-compose
            mode: 0755
      become: yes
    - name: Сompletion installation
      block:
        - name: adding user to the group of users
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: true
        - name: Reloading
          reboot:
      become: yes